MONGO_CONNECTION_STRING = "mongodb+srv://Student:student123@studentmgmtcluster.hn1j5la.mongodb.net/?retryWrites=true&w=majority&appName=StudentMgmtCluster"
ADMIN_USER = "admin"
ADMIN_PASS = "admin123"
ALLOWED_WIFI_SSID = "TECHSKILLS" 
ALLOWED_MAC_ADDRESS = "00:5f:67:9a:4d:c3"